### ISSUE TITLE
Support for [Route] and Http Methods Attributes.

### ISSUE THREAD

**Issue by Morasiu** [sleeuwen/UrlActionGenerator#1]
Hey, that library looks great. I've always wanted something like this!

Does it support `[Route]` attribute and `[HttpGet("product")]` (and similar) attributes?

**Comment by sleeuwen** [comment]
Hi Morasiu,

The methods generated by the library is just a strongly typed facade for the standard `Url.Action("Action", "Controller")` (or `asp-controller="Controller" asp-action="Action"` in razor) that you would normally use.
Because of that, urls are always correctly generated even when using custom `[Route()]` or `[HttpGet()]` attributes.

**Comment by Morasiu** [comment]
Great to hear!

I suggest marking that in README.md for clarification :)
