### ISSUE TITLE
Generator Not Running (v4.0-alpha.1)

### ISSUE THREAD

**Issue by thepigeonfighter** [sleeuwen/UrlActionGenerator#5]
Hey was checking out version 0.4.0-alpha.1. I added the nuget to my solution. Rebuilt/Cleaned/ closed and restarted visual studio but could not get the generator to generate any paths. The project targets .net5.0. I also tried adding the attributes `OutputItemType="Analyzer" ReferenceOutputAssembly="false"` to the reference in case that would make a difference, but it did not. I can see it shows up under the Analyzer root in Visual Studio 
![Untitled](https://user-images.githubusercontent.com/33707144/116607860-83b98600-a900-11eb-92d8-2c506b50d47f.png)
But appears to not have any generated files under it. 
Any suggestions?  Thanks

**Comment by sleeuwen** [comment]
Hey, I'm sorry to hear that it's not working out of the box for you, I've tested it on the new project template for razor pages and that seemed to work for me. Can you verify that it also works for you if you create a new project and add the reference. 

If the new project works (so we can assume the source generator is being called in your project as well), there can probably be one of two things, 1. It couldn't find any .cshtml files with the `@page` directive at the top. Or 2. It did find some pages but threw an exception before being able to generate the code. 

For 2. I plan on adding some diagnostics so you at least get a warning saying something wasn't working correctly and the exceptions details.  For 1. I'm not sure, I'm using what feels like a "hacky" way to read the cshtml files but am not proficient enough with msbuild to get it working correctly. So what I'm currently doing is I try to find the directory the source project is in and look in that directory for .cshtml files. I will probably also add a diagnostic when no pages or controllers are found so we can see more easily why it isn't generating anything. 

If you feel adventageous you can also add the UrlActionGenerator.csproj as a project to your solution and change the PackageReference to a ProjectReference with  those extra attributes so you can debug the generator and see why it's not working. Otherwise if the new project template works you could try to narrow down why it doesn't work for your project and see if you can find a minimum repro for the issue. 

I will do some more experimenting myself to find any issues but I don't really have any large projects that use razor pages so I probably can't find everything. I really appreciate you taking the time to try out the alpha version and finding these bugs before release.

**Comment by thepigeonfighter** [comment]
So I cloned the project and narrowed down that it is indeed was throwing an exception before it could generate any code.
 In the file PageDiscoverer.cs ln 28 was throwing an error because `PageData` did not implement `IComaparable`. I changed the line from `group.OrderBy(page=> page)` to `group.OrderBy(page=> page.PageName)` wasn't exactly sure how you wanted them ordered and that seemed to work. But the fly in the ointment is that even after that the script was not generated. I stepped through the generation and could see it did indeed add a file to the context but something is happening to where the other solution isn't getting the file somehow. I did have several warnings that I wasn't sure about. Not sure if this would be related. 
```
 1>C:\Program Files\dotnet\sdk\5.0.104\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(207,5): warning NU5128: Some target frameworks declared in the dependencies group of the nuspec and the lib/ref folder do not have exact matches in the other location. Consult the list of actions below:
1>C:\Program Files\dotnet\sdk\5.0.104\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(207,5): warning NU5128: - Add lib or ref assemblies for the netstandard2.0 target framework
```
I will look at this more tomorrow. 


### Update
After messing around with this more I upgraded  
`<PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="3.8.0" PrivateAssets="All" />`
to version 3.9.0. This gave me an warning saying the generator couldn't be generated because  Microsoft.CodeAnalysis.CSharp version 3.9.0 couldn't be found. I tried everything I could(i.e. deleting the bin/obj/.vs folder to get it to realize that I did actually have that package installed but could not get that warning to go away. After some googling I saw a suggestion to update Visual Studio which I didn't think about but I am actually running version 16.8.5. So this issue might be fixed by upgrading, but I can't upgrade on my work network so I'll try to get the update done on Monday and let you know if that solves the issue.

**Comment by sleeuwen** [comment]
Hi,

I've looked into this the last few days and have now published version 0.4.0-alpha.4 to nuget. I've also tested this version on the Contoso University sample project referred to in the ASP.NET Core documents for both the MVC and Razor Pages variants and they seem to be working for me with the latest version (there were some other issues there that I have resolved as well). 

For the IComparable, I removed that because I thought it wasn't needed anymore but apparently it was, I have reworked this so it really isn't needed anymore. I have also added diagnostics for when an unhandled exception occurs so you at least get a warning message there was an exception during generation. Finally I removed the check to not output the generated file it there are no controllers/pages so when it can't find any pages at least it will show a file that it ran (which should make debugging easier in the future).

The warnings you got are not related as far as I'm aware, I believe it triggers because the nupkg doesn't contain a lib/ folder because it is only an analyzer/source generator.

The real problem was that I work mostly on Linux and use JetBrains Rider to test it out, which is subtly different in how it runs source generators compared to VS and I was using something that wasn't available when ran through VS. I've changed this and tested the alpha.4 version in windows with VS and that is working for me as well.

Can you check if the 0.4.0-alpha.4 version works for you? I've also updated the feature/razor-pages branch with the latest changes so if it doesn't work you can try to debug it with the latest changes. If you want to do that, you now also need to add an `<Import />` to the csproj of your project like is done in the [AspNetCoreSamplePages project](https://github.com/sleeuwen/UrlActionGenerator/blob/feature/razor-pages/samples/AspNetCoreSamplePages/AspNetCoreSamplePages.csproj#L9). This is automatically included when using the nuget package.

**Comment by thepigeonfighter** [comment]
We have lift off! I am now getting a compiled file and no issues from the nuget integration. I am getting some unexpected routes though. For example I have this route :
`Url.Pages().Projects.IndexProjectYears()`
The output I am expecting is this :  
`/Projects/Index?handler=ProjectYears`
but I am getting 
`/Projects?pageHandler=projectYears`
This route is generated from the file 
`/Pages/Projects/Index.cshtml.cs`
For the action 
`public IActionResult OnGetProjectYears()`

I've always used the term `?handler`, `pageHandler` appears not to be working for me, not sure if it is a project setting or what. In addition `Url.Pages().Projects.IndexProjectYears()` seems a little confusing to me. Not exactly sure how to make it clearer. Maybe something like `Url.Pages().Projects.Handlers.ProjectYears()` or `Url.Pages().Projects.Index.ProjectYears()`? Not sure just a suggestion and totally not a big deal. Thanks for working on this issue.

**Comment by sleeuwen** [comment]
Great to hear the nuget is working now!

Ahh, you're right about the `?handler`, guess I was confused with the fact that you need to use `asp-page-handler=""` in the views, but indeed that does `?handler=` and not `?pageHandler=`, I will fix that in a moment and publish an 0.4.0-alpha.5 release. The fact that you're missing the /Index at the end is the default behavior I believe because Index is the default page, so the result should be `/Projects?handler=ProjectYears`

For the API, I'm open for suggestions on how it can be improved (not only for razor pages but also in general). For now I prefix the page handler by the page name as they are only unique for that page, but I agree it is weird to see `IndexProjectYears`. Works something like this be better in your opinion: `Url.Pages().Projects.IndexHandlers.ProjectYears()`? I can't do just `.Handlers.ProjectYears()` because they are only unique per page, and I can't do `.Index.ProjectYears()` because they would break `.Index()`.

**Comment by thepigeonfighter** [comment]
That makes sense about the not including  `/index` for pages.  Yes  I think  `Url.Pages().Projects.IndexHandlers.ProjectYears()` is much clearer to me at least!

**Comment by sleeuwen** [comment]
Alright, I've uploaded 0.4.0-alpha.5 to nuget with the changes for `?handler=` and `Url.Pages().Projects.IndexHandlers.ProjectYears()`. Let me know if this works correctly or if you find any other problems.

**Comment by thepigeonfighter** [comment]
Working great! Slowly starting to replace magic strings with this through-out the project so I'll keep you posted on how its going. Another bug I found might be a little trickier to handle. So when it comes to `POST` page handlers the string it generates will probably have to be different. But not sure how to handle it. So I have a page handler that looks like this for example : 
`public IActionResult OnPostReadComments([DataSourceRequest] DataSourceRequest request)`
So when you go to create a url from the generator you do something like this :
`Url.Pages().Support.IndexHandlers.ReadComments(new DataSourceRequest() { Page = 10, PageSize = 20})`
which then generates the route :
`/Support?handler=ReadComments&request=Kendo.Mvc.UI.DataSourceRequest`
When it comes to `POST` pagehandler unless the method param has a `[FromQuery]` attribute it seems like it should be excluded from the url and considered to be body or form data, but it seems like there would also be exceptions to this rule. Like a post to `/contact/edit/1`. We clearly need to keep the '1' in the route. Not sure if a parameter being a primitive would be enough info to know that it should be encoded into the url. 

In addition I'm thinking it might be handy to be able to access these routes directly instead of using the `IUrlHelper` extension. I can do this currently by doing something like ` UrlActionGenerator_UrlHelperExtensions.Pages()....` but this is a little long winded. Not sure if you could provide a type with a simpler name that could be accessed in places without having to inject a `IUrlHelper` extension. For example setting readonly properties in a view model.

**Comment by sleeuwen** [comment]
Awesome that you're using it already in your project and finding these issues.
I've done some more testing on the complex parameters (for MVC only though, so might be different for razor pages which I will check later), and from what I found is when you don't specify one of `[FromQuery]`, `[FromForm]`, etc. the model can be populated from multiple sources (so one part through querystring and another part with form body). Because of that I don't think it's really possible to just ignore complex types. The argument that I can ignore complex types would be that you also can't pass complex types to `@Url.Action()`. If you don't want any parameters added as query parameters you can pass `null` as model, otherwise I may need to check if a property is set and add that as query parameter (but that would also have a lot of complications).

One thing that I thought of I'm still missing when you mentioned `[FromQuery]` is that I can ignore parameters that have `[FromBody]` or `[FromForm]`. I'll add that as well.

Can you explain in a bit more detail how you're using the `UrlActionGenerator_UrlHelperExtensions.Pages()...` directly? because those classes also need the `IUrlHelper` as constructor parameter and they call into the `IUrlHelper` to generate the urls and in that case you can already call the method on the `IUrlHelper` instance.

**Comment by thepigeonfighter** [comment]
I'm not super familiar with the actual model binding process, that is still "magic" to me at this point so I figured I was missing something.  So the first example I ran into was setting a link in a view model. I could do that directly inside a controller or page model but it'd be handy to be able to do it on the view model itself.  Here is an example 
~~~C#
    public class ApplicationShortVM : ILinkable
    {
        public int ApplicationID { get; set; }
        public string Link => "/Applications/Details/" + ApplicationID;
        public string Guide { get; set; }
        public string ApplicationDateString { get; set; }

        [DisplayName("Programme Type")]
        public string ProgrammeType { get; set; }

        public string Status { get; set; }
    }
~~~

### Update
In addition to the above example I have some smoke tests that hit a bunch of urls and make sure they all resolve. These are currently  using strings. But they could be helped by accessing the routes via your api.

**Comment by thepigeonfighter** [comment]
An additional small issue I discovered is with page models and properties that are populated from routes.  For example I have this property 
~~~C#
[FromRoute]
public int ysiRef { get; set; }
~~~
The method that is generated for this page correctly expects a parameter named `ysiRef` but the parameter is a `string` instead of an `int`.

**Update**
Sorry I keep adding things. I just noticed with the version I'm using (0.4.0-alpha.5) seems to not generate Index  page for page models anymore? 
I have a page `Pages/Speakouts/Index.cshtml`
It has a couple page handlers which are accessed by `Url.Pages().Speakouts.IndexHandlers` but I don't see `Url.Pages().Speakouts.Index()` anymore? Not sure what the cause behind this is.

**Comment by sleeuwen** [comment]
Thanks on your example for the creating the URL in the ViewModel. From your previous post I got the impression you were actually using the generated class to create the URL but I understand that is what you actually want to do and not currently doing.

From the start I chose to use extension methods on the `IUrlHelper` interface so I can use that to do the actual generation of the URLs. The reason is because the generating of the URLs can be quite complicated and I'd rather not reimplement that (for example, in MVC you can add multiple `[Route]` attributes on an action method with different route parameters and it will match which one to use based on the arguments, also you can add global prefixes in Startup.cs).

A possible solution for your ViewModel would be to change the `Link` to a method that accepts an `IUrlHelper` and call the extension method on that, but I understand that is probably not possible in the smoke tests.

```C#
public class ApplicationShortVM : ILinkable
{
    public string Link(IUrlHelper url) => url.Pages().Application.Details(ApplicationID);
}
```

The issue with `[FromRoute]` is because I didn't add that to the allowed attributes for properties, I've added it now and will release alpha 6 shortly.

The last issue which your Speakouts page, do you maybe have no `OnGet(Async)` method in the code-behind for that page? if you only have the handler methods like `OnGetXxx()` but no `OnGet()` this could happen and will also be fixed in alpha 6.

**Comment by thepigeonfighter** [comment]
This all makes sense to me. Nice work! This issue is closed as far as I'm concerned. Thanks for all your work.
